import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../../../config/design_tokens.dart';
import '../../../core/network/api_client.dart';
import '../../../shared/models/models.dart';
import '../../parking/data/providers.dart';
import '../data/repositories.dart';

DateTime selectedStart = DateTime.now().add(const Duration(days: 1));
DateTime selectedEnd = selectedStart.add(const Duration(hours: 2));
String _money(int cents) => '${(cents / 100).toStringAsFixed(2).replaceAll('.', ',')} €';
String _date(DateTime value) => '${value.day.toString().padLeft(2, '0')}.${value.month.toString().padLeft(2, '0')}.${value.year} · ${value.hour.toString().padLeft(2, '0')}:${value.minute.toString().padLeft(2, '0')}';

class BetaScaffold extends ConsumerWidget {
  const BetaScaffold({super.key, required this.title, required this.child, this.actions});
  final String title; final Widget child; final List<Widget>? actions;
  @override Widget build(BuildContext context, WidgetRef ref) {
    final mode = ref.watch(appModeProvider);
    return Scaffold(backgroundColor: T.porcelain, appBar: AppBar(title: Text(title), actions: actions), body: Column(children: [
      if (mode == AppMode.localBeta) Container(width: double.infinity, color: T.amberSoft, padding: const EdgeInsets.all(12), child: const Text('Lokaler Beta-Modus – Buchungen werden nur auf diesem Gerät gespeichert.', textAlign: TextAlign.center, style: TextStyle(fontWeight: FontWeight.w700))),
      if (mode == AppMode.checking) const LinearProgressIndicator(),
      if (mode == AppMode.unavailable) Material(color: T.inkSoft, child: ListTile(title: const Text('API nicht erreichbar.', style: TextStyle(color: Colors.white)), trailing: TextButton(onPressed: ref.read(appModeProvider.notifier).check, child: const Text('Erneut versuchen')))),
      Expanded(child: child),
    ]));
  }
}

class ParkingDetailScreen extends ConsumerStatefulWidget { const ParkingDetailScreen({super.key, required this.id}); final String id; @override ConsumerState<ParkingDetailScreen> createState()=>_ParkingDetailState(); }
class _ParkingDetailState extends ConsumerState<ParkingDetailScreen> {
  bool saved=false;
  @override Widget build(BuildContext context) {
    final state=ref.watch(parkingSpaceProvider(widget.id));
    return BetaScaffold(title:'Stellplatz', child: state.when(
      loading:()=>const Center(child:CircularProgressIndicator()),
      error:(_,__)=>_Retry(message:'Stellplatz konnte nicht geladen werden.', onRetry:()=>ref.invalidate(parkingSpaceProvider(widget.id))),
      data:(space)=>space==null?const Center(child:Text('Stellplatz nicht gefunden.')):_detail(space),
    ));
  }
  Widget _detail(ParkingSpace space) {
    final hours=selectedEnd.difference(selectedStart).inHours.clamp(1,24);
    return SingleChildScrollView(padding:const EdgeInsets.all(24), child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:980), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[
      Container(height:260, decoration:BoxDecoration(gradient:const LinearGradient(colors:[T.inkSoft,T.ink]),borderRadius:BorderRadius.circular(T.radius)),child:Center(child:Icon(space.covered?Icons.garage_rounded:Icons.local_parking_rounded,size:100,color:T.mint))),
      const SizedBox(height:24), Row(children:[Expanded(child:Text(space.title,style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900))),IconButton(onPressed:()=>setState(()=>saved=!saved),icon:Icon(saved?Icons.bookmark:Icons.bookmark_border)),Text(saved?'Gemerkt':'Merken')]),
      Text('${space.district} · nahe ${space.landmark} · ${space.walkingMinutes} Min. zu Fuß',style:const TextStyle(color:T.muted)), const SizedBox(height:18),
      Wrap(spacing:10,children:[if(space.verified)_tag('✓ Verifiziert'),_tag('★ ${space.rating} (${space.reviewCount})'),_tag(space.accessLabel()),if(space.covered)_tag('Überdacht'),if(space.ev)_tag('E-Laden')]), const SizedBox(height:20),
      _panel(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Zeitraum wählen',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),BookingTimeSelector(onChanged:()=>setState((){})),Text('${_money((space.hourlyPrice*100*hours).round())} gesamt',style:const TextStyle(fontWeight:FontWeight.w800))])),const SizedBox(height:16),
      _panel(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(space.dimensions()),Text(space.cancellationSummary),const Text('Die genaue Adresse und Zufahrt werden nach bestätigter Buchung freigeschaltet.')])),const SizedBox(height:24),
      SizedBox(width:double.infinity,child:FilledButton(onPressed:() async { final path='/checkout/${space.id}'; final auth=ref.read(authRepositoryProvider); if(!auth.authenticated) await auth.restore(); if(!context.mounted)return; context.go(auth.authenticated?path:'/login?returnTo=${Uri.encodeComponent(path)}'); }, child:const Text('Jetzt reservieren'))),
    ]))));
  }
}

class BookingTimeSelector extends StatefulWidget {const BookingTimeSelector({super.key,required this.onChanged});final VoidCallback onChanged;@override State<BookingTimeSelector> createState()=>_TimeState();}
class _TimeState extends State<BookingTimeSelector>{
 @override Widget build(BuildContext context)=>Wrap(spacing:12,children:[OutlinedButton.icon(icon:const Icon(Icons.calendar_today),label:Text(_date(selectedStart)),onPressed:() async{final d=await showDatePicker(context:context,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:90)),initialDate:selectedStart);if(d!=null){selectedStart=DateTime(d.year,d.month,d.day,selectedStart.hour);selectedEnd=selectedStart.add(const Duration(hours:2));widget.onChanged();setState((){});}}),DropdownButton<int>(value:selectedStart.hour,items:[8,10,12,14,16,18,20].map((h)=>DropdownMenuItem(value:h,child:Text('${h.toString().padLeft(2,'0')}:00 Uhr'))).toList(),onChanged:(h){if(h!=null){selectedStart=DateTime(selectedStart.year,selectedStart.month,selectedStart.day,h);selectedEnd=selectedStart.add(const Duration(hours:2));widget.onChanged();setState((){});}})]);
}

class AuthScreen extends ConsumerStatefulWidget {const AuthScreen({super.key,required this.register,this.returnTo});final bool register;final String? returnTo;@override ConsumerState<AuthScreen> createState()=>_AuthState();}
class _AuthState extends ConsumerState<AuthScreen>{
 final name=TextEditingController(),email=TextEditingController(),password=TextEditingController();bool accepted=false,busy=false;String? error;
 @override void dispose(){name.dispose();email.dispose();password.dispose();super.dispose();}
 @override Widget build(BuildContext context)=>BetaScaffold(title:widget.register?'Konto erstellen':'Anmelden',child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:480),child:_panel(Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(widget.register?'Willkommen bei FREIRAUM':'Schön, dich wiederzusehen',style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),if(widget.register)TextField(controller:name,decoration:const InputDecoration(labelText:'Name')),TextField(controller:email,decoration:const InputDecoration(labelText:'E-Mail')),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Passwort (mindestens 8 Zeichen)')),if(widget.register)CheckboxListTile(contentPadding:EdgeInsets.zero,value:accepted,onChanged:(v)=>setState(()=>accepted=v??false),title:const Text('Ich akzeptiere die Beta-Bedingungen.')),if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)),const SizedBox(height:12),FilledButton(onPressed:busy?null:_submit,child:Text(busy?'Bitte warten …':widget.register?'Registrieren':'Anmelden')),TextButton(onPressed:(){final p=widget.register?'/login':'/register';context.go(widget.returnTo==null?p:'$p?returnTo=${Uri.encodeComponent(widget.returnTo!)}');},child:Text(widget.register?'Bereits registriert? Anmelden':'Noch kein Konto? Registrieren'))]))))));
 Future<void> _submit()async{if(widget.register&&!accepted){setState(()=>error='Bitte akzeptiere die Beta-Bedingungen.');return;}setState((){busy=true;error=null;});try{final auth=ref.read(authRepositoryProvider);if(widget.register){await auth.register(name.text,email.text,password.text);}else{await auth.login(email.text,password.text);}if(mounted)context.go(widget.returnTo??'/bookings');}catch(e){if(mounted)setState(()=>error=e is ApiException||e is FormatException?e.toString():'Anmeldung nicht möglich.');}finally{if(mounted)setState(()=>busy=false);}}
}

class CheckoutScreen extends ConsumerStatefulWidget {const CheckoutScreen({super.key,required this.id});final String id;@override ConsumerState<CheckoutScreen> createState()=>_CheckoutState();}
class _CheckoutState extends ConsumerState<CheckoutScreen>{
 List<VehicleRecord>? vehicles;String? selectedVehicleId,error;bool busy=false;final vehicleName=TextEditingController(),plate=TextEditingController(),height=TextEditingController(),width=TextEditingController(),length=TextEditingController();
 @override void initState(){super.initState();_loadVehicles();}
 @override void dispose(){for(final c in [vehicleName,plate,height,width,length])c.dispose();super.dispose();}
 Future<void> _loadVehicles()async{try{final values=await ref.read(vehicleRepositoryProvider).all();if(mounted)setState((){vehicles=values;selectedVehicleId=values.where((v)=>v.isDefault).firstOrNull?.id??values.firstOrNull?.id;});}catch(e){if(mounted)setState(()=>error=e.toString());}}
 @override Widget build(BuildContext context){final space=ref.watch(parkingSpaceProvider(widget.id));return BetaScaffold(title:'Reservierung prüfen',child:space.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(_,__)=>_Retry(message:'Stellplatz konnte nicht geladen werden.',onRetry:()=>ref.invalidate(parkingSpaceProvider(widget.id))),data:(s)=>s==null?const Center(child:Text('Stellplatz nicht gefunden.')):_checkout(s)));}
 Widget _checkout(ParkingSpace space){final mode=ref.watch(appModeProvider);final selected=vehicles?.where((v)=>v.id==selectedVehicleId).firstOrNull;final fits=selected!=null&&selected.height<=space.maxHeight&&selected.width<=space.maxWidth&&selected.length<=space.maxLength;final total=(space.hourlyPrice*100*selectedEnd.difference(selectedStart).inHours.clamp(1,24)).round();return SingleChildScrollView(padding:const EdgeInsets.all(24),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:720),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_panel(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(mode==AppMode.localBeta?'Lokale Beta-Reservierung ohne Online-Zahlung':'Live-Reservierung ohne Online-Zahlung',style:const TextStyle(color:T.warning,fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:12),Text(space.title,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),Text(space.approximate()),const Divider(),const Text('Fahrzeug',style:TextStyle(fontWeight:FontWeight.w900)),if(vehicles==null)const LinearProgressIndicator(),if(vehicles?.isEmpty??false)const Text('Lege zuerst ein Fahrzeug mit vollständigen Maßen an.'),if(vehicles?.isNotEmpty??false)DropdownButtonFormField<String>(value:selectedVehicleId,items:vehicles!.map((v)=>DropdownMenuItem(value:v.id,child:Text('${v.name} · ${v.plate}'))).toList(),onChanged:(v)=>setState(()=>selectedVehicleId=v),decoration:const InputDecoration(labelText:'Fahrzeug auswählen')),TextButton.icon(onPressed:_showAddVehicle,icon:const Icon(Icons.add),label:const Text('Fahrzeug hinzufügen')),if(selected!=null&&!fits)const Text('Dieses Fahrzeug passt nicht in den Stellplatz.',style:TextStyle(color:Colors.red,fontWeight:FontWeight.w800)),const Divider(),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Voraussichtlicher Gesamtpreis'),Text(_money(total),style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900))]),const Text('Der verbindliche Gesamtpreis wird vom Server bestätigt.',style:TextStyle(color:T.muted))])),if(error!=null)Padding(padding:const EdgeInsets.all(12),child:Text(error!,style:const TextStyle(color:Colors.red))),FilledButton(onPressed:busy||!fits?null:()=>_confirm(space,selected!,total),child:Text(busy?'Verfügbarkeit wird geprüft …':'Reservierung bestätigen'))]))));}
 Future<void> _showAddVehicle()async{vehicleName.clear();plate.clear();height.clear();width.clear();length.clear();await showDialog<void>(context:context,builder:(c)=>AlertDialog(title:const Text('Fahrzeug hinzufügen'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:vehicleName,decoration:const InputDecoration(labelText:'Bezeichnung')),TextField(controller:plate,decoration:const InputDecoration(labelText:'Kennzeichen')),TextField(controller:height,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Höhe in m')),TextField(controller:width,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Breite in m')),TextField(controller:length,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Länge in m'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Abbrechen')),FilledButton(onPressed:()async{final dimensions=[height,width,length].map((c)=>double.tryParse(c.text.replaceAll(',','.'))).toList();if(vehicleName.text.trim().isEmpty||plate.text.trim().isEmpty||dimensions.any((v)=>v==null||v<=0)){setState(()=>error='Bitte gib Bezeichnung, Kennzeichen und alle Maße an.');return;}final saved=await ref.read(vehicleRepositoryProvider).save(VehicleRecord(id:'',name:vehicleName.text.trim(),plate:plate.text.trim().toUpperCase(),height:dimensions[0]!,width:dimensions[1]!,length:dimensions[2]!,isDefault:vehicles?.isEmpty??true));if(c.mounted)Navigator.pop(c);await _loadVehicles();if(mounted)setState(()=>selectedVehicleId=saved.id);},child:const Text('Speichern'))]));}
 Future<void> _confirm(ParkingSpace space,VehicleRecord vehicle,int total)async{setState((){busy=true;error=null;});try{var availability=await ref.read(availabilityRepositoryProvider).check(space.id,selectedStart,selectedEnd);if(!availability.available)throw ApiConflictException(availability.message??'Der Zeitraum ist nicht verfügbar.');availability=await ref.read(availabilityRepositoryProvider).check(space.id,selectedStart,selectedEnd);if(!availability.available)throw ApiConflictException(availability.message??'Der Zeitraum ist nicht verfügbar.');final seed=DateTime.now().microsecondsSinceEpoch.toString();final created=await ref.read(bookingRepositoryProvider).create(BookingRecord(id:seed,parkingId:space.id,title:space.title,reference:'FR-${seed.substring(seed.length-6)}',vehicleId:vehicle.id,plate:vehicle.plate,status:'confirmed',start:selectedStart,end:selectedEnd,hourlyPriceCents:(space.hourlyPrice*100).round(),totalCents:total));if(mounted)context.go('/booking/${created.id}/confirmed');}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
}

class ConfirmationScreen extends ConsumerWidget {const ConfirmationScreen({super.key,required this.id});final String id;@override Widget build(BuildContext context,WidgetRef ref)=>BetaScaffold(title:'Reservierung bestätigt',child:FutureBuilder<BookingRecord?>(future:ref.read(bookingRepositoryProvider).detail(id),builder:(context,s){if(!s.hasData)return s.connectionState==ConnectionState.done?const Center(child:Text('Buchung nicht gefunden.')):const Center(child:CircularProgressIndicator());final b=s.data!;return SingleChildScrollView(padding:const EdgeInsets.all(24),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:680),child:_panel(Column(children:[const Icon(Icons.check_circle,color:T.success,size:72),const Text('Dein Stellplatz ist reserviert',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),if(b.localBeta)const Text('Lokale Beta-Buchung',style:TextStyle(color:T.warning,fontWeight:FontWeight.w800)),Text(b.title),Text('${_date(b.start)} · ${b.plate}'),Text('Buchungsnummer ${b.reference}'),Text('Serverbestätigter Gesamtpreis: ${_money(b.totalCents)}'),const SizedBox(height:16),FilledButton.icon(onPressed:()=>context.go('/bookings/${b.id}/pass'),icon:const Icon(Icons.qr_code),label:const Text('Parking Pass öffnen')),TextButton(onPressed:()=>context.go('/bookings'),child:const Text('Alle Buchungen'))])))));}));}

class BookingsScreen extends ConsumerStatefulWidget {const BookingsScreen({super.key});@override ConsumerState<BookingsScreen> createState()=>_BookingsState();}
class _BookingsState extends ConsumerState<BookingsScreen>{late Future<List<BookingRecord>> future;@override void initState(){super.initState();future=_load();}Future<List<BookingRecord>> _load()async{final auth=ref.read(authRepositoryProvider);if(!auth.authenticated)await auth.restore();return ref.read(bookingRepositoryProvider).all();}void reload()=>setState(()=>future=_load());@override Widget build(BuildContext context)=>BetaScaffold(title:'Meine Buchungen',actions:[IconButton(onPressed:()async{await ref.read(authRepositoryProvider).logout();if(context.mounted)context.go('/login');},icon:const Icon(Icons.logout))],child:FutureBuilder<List<BookingRecord>>(future:future,builder:(context,s){if(s.hasError)return _Retry(message:s.error.toString(),onRetry:reload);if(!s.hasData)return const Center(child:CircularProgressIndicator());final bookings=s.data!;if(bookings.isEmpty)return Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Noch keine Buchungen',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),TextButton(onPressed:()=>context.go('/discover'),child:const Text('Stellplatz entdecken'))]));return RefreshIndicator(onRefresh:()async{reload();await future;},child:ListView(padding:const EdgeInsets.all(24),children:bookings.map((b)=>_BookingCard(b,onChanged:reload)).toList()));}));}
class _BookingCard extends ConsumerWidget {const _BookingCard(this.booking,{required this.onChanged});final BookingRecord booking;final VoidCallback onChanged;@override Widget build(BuildContext context,WidgetRef ref)=>Padding(padding:const EdgeInsets.only(bottom:14),child:_panel(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(booking.title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900))),Text(booking.status=='cancelled'?'Storniert':'Bestätigt')]),Text('${_date(booking.start)} · ${booking.plate}'),Text('${booking.reference} · ${_money(booking.totalCents)}'),if(booking.localBeta)const Text('Lokale Beta-Buchung',style:TextStyle(color:T.warning)),if(booking.status!='cancelled')Wrap(children:[TextButton(onPressed:()=>context.go('/bookings/${booking.id}/pass'),child:const Text('Parking Pass öffnen')),TextButton(onPressed:()async{final yes=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Buchung stornieren?'),content:const Text('Die Stornierungsbedingungen deiner Buchung werden angewendet.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Behalten')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Stornieren'))]));if(yes==true){await ref.read(bookingRepositoryProvider).cancel(booking.id);onChanged();}},child:const Text('Stornieren'))])])));}

class ParkingPassScreen extends ConsumerWidget {const ParkingPassScreen({super.key,required this.id});final String id;@override Widget build(BuildContext context,WidgetRef ref)=>BetaScaffold(title:'Parking Pass',child:FutureBuilder<BookingRecord?>(future:ref.read(bookingRepositoryProvider).detail(id),builder:(context,s){if(!s.hasData)return s.connectionState==ConnectionState.done?const Center(child:Text('Buchung nicht gefunden.')):const Center(child:CircularProgressIndicator());final b=s.data!;if(b.status!='confirmed')return const Center(child:Text('Dieser Parking Pass ist nicht mehr gültig.'));final token=b.localBeta?'LOCAL-BETA-PASS:${b.id}':b.parkingPassToken;if(token==null||token.isEmpty)return const Center(child:Text('Parking Pass konnte nicht geladen werden.'));return SingleChildScrollView(padding:const EdgeInsets.all(24),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:_panel(Column(children:[const Text('FREIRAUM',style:TextStyle(letterSpacing:4,fontSize:28,fontWeight:FontWeight.w900)),if(b.localBeta)const Text('LOKALER BETA-PASS',style:TextStyle(color:T.warning,fontWeight:FontWeight.w900)),QrImageView(data:token,size:210),Text(b.title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900),textAlign:TextAlign.center),Text('${_date(b.start)} – ${_date(b.end)}'),Text(b.plate),if(!b.localBeta&&b.exactAddress!=null)...[const Divider(),Text(b.exactAddress!),if(b.entranceInstructions!=null)Text(b.entranceInstructions!),if(b.accessCode!=null)Text('Zugangscode: ${b.accessCode}')],const Text('Diesen Pass nicht teilen.',style:TextStyle(color:T.warning,fontWeight:FontWeight.w800))])))));}));}

class _Retry extends StatelessWidget {const _Retry({required this.message,required this.onRetry});final String message;final VoidCallback onRetry;@override Widget build(BuildContext context)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(message,textAlign:TextAlign.center),TextButton(onPressed:onRetry,child:const Text('Erneut versuchen'))]));}
Widget _tag(String text)=>Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:T.mintSoft,borderRadius:BorderRadius.circular(20)),child:Text(text,style:const TextStyle(fontWeight:FontWeight.w700)));
Widget _panel(Widget child)=>Container(width:double.infinity,padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:T.surface,borderRadius:BorderRadius.circular(T.radius),border:Border.all(color:T.line),boxShadow:T.shadowSmall),child:child);
